nelmio_cors:
  nelmio_cors:
    defaults:
      allow_origin: ["http://localhost:8080"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["content-type", "authorization"]
      expose_headers: ["Link"]
      max_age: 3600
    paths:
      "^/api/":
        allow_origin: ["http://localhost:8080"]
        allow_methods: ["GET", POST', "PUT", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age: 3600
